services:
    # Servidor de Aplicación (PHP-FPM)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel
        container_name: laravel-application
        restart: unless-stopped
        working_dir: /var/www
        ports:
            - "5173:5173"

        environment:
            - VITE_PORT=5173
        volumes:
            - ./:/var/www
        networks:
            - laravel-network

        depends_on:
            - mysql
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # Servidor Web (Nginx)
    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel-network
        depends_on:
            - app

    # Base de Datos (MySQL)
    mysql:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
